### ISSUE TITLE
directConnection forced on MongoClient v4

### ISSUE THREAD

**Issue by rafalgajda-silvair** [avanzu/node-packages#1]
Hi,

The `connectV4` method for mongodb in `eventstore`: `packages/node-eventstore/lib/databases/mongodb.js:209` forces MongoClient to connect with direct connection:
```
this.client = new MongoClient(connectionUrl, {
    ...options,
    appName: 'node-eventstore',
    directConnection: true,
})
```
Was that somehow necessary for mongodb 4.x? It isn't set for other versions and the default is `false` (same as for mongodb 3.x). 
I'm asking because we're using SRV links to connect to MongoDB and that option block us from doing that: 
```
MongoAPIError: SRV URI does not support directConnection
```

I've checked and removing `directConnection` and using SRV link works (at least as far as connecting go).
So would it be possible to remove that option? Or at least reorganizing them so it can be overwritten with `options`:
```
this.client = new MongoClient(connectionUrl, {
    directConnection: true,
    ...options,
    appName: 'node-eventstore',
})
```

I can open a PR if you'd like.

**Comment by avanzu** [comment]
Not sure why this is arranged that way. There is no reason why you shouldn't be able to override those options. That's why they are there, afterall. 

With the latest release you should have full control over the connection options.

**Comment by rafalgajda-silvair** [comment]
Thank you :)
